demo/Demo.Http/Controllers/CookieControlController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Demo.Http.Controllers
{
    public class CookieControlController : Controller
    {
        // GET: CookieControl
        public ActionResult Start(string Action=null , string CookieName = null ,  string CookieValue = null , string RemoteMode = null, string GetCookieName = null)
        {
            if (string.IsNullOrEmpty(Action)) return View();
            if (Action == "SetRemoteCookie")
            {
                var Cookie = new HttpCookie(CookieName, CookieValue);
                if (RemoteMode == "HttpOnly")
                    Cookie.HttpOnly = true;
                Cookie.Expires = DateTime.Now.AddDays(1);
                Response.AppendCookie(Cookie);
            }
            if (Action == "RemoveRemoteCookie")
            {
                var Cookie = new HttpCookie(GetCookieName);
                Cookie.Expires = DateTime.Now.AddDays(-3);
                Response.Cookies.Add(Cookie);
            }
            return View();
        }
    }
}

demo/Demo.Http/Views/CookieControl/Start.cshtml
@{
    ViewBag.Title = "Start";
    var PageUrl = Url.Action("Start","CookieControl");
}

<h4>Cookie Client Control</h4>
<form action="@PageUrl" method="post">
    Name：<input type="text" id="setCookieName" name="CookieName" /><br />
    Value：<input type="text" id="setCookieValue" name="CookieValue" /><br />
    <input type="button" value="SetCookie" onclick="setClientCookie()" />
    <input type="checkbox" id="RemoteMode" name="RemoteMode" value="HttpOnly" /><label for="RemoteMode">HttpOnly</label>
    <input type="submit" name="Action" value="SetRemoteCookie" /><br /><br />
    Name：<input type="text" name="GetCookieName" id="getCookieName" /> = <input type="text" id="getCookieValue" /><br />
    <input type="button" value="GetCookie" onclick="getClientCookie()" /><br />
    <input type="button" value="RemoveCookie" onclick="removeClientCookie()" /><input type="submit" name="Action" value="RemoveRemoteCookie" /><br /><br /><br />
</form>

<h4>localStorage Control</h4>
Name：<input type="text" id="setLocalStorageName" /><br />
Value：<input type="text" id="setLocalStorageValue" /><br />
<button onclick="setLocalStorage()">SetLocalStorage</button><br /><br />
Name：<input type="text" id="getLocalStorageName" /> = <input type="text" id="getLocalStorageValue" /><br />
<button onclick="getLocalStorage()">GetLocalStorage</button><br />
<button onclick="removeLocalStorage()">RemoveLocalStorage</button><br /><br /><br />


<h4>sessionStorage Control</h4>
Name：<input type="text" id="setSessionStorageName" /><br />
Value：<input type="text" id="setSessionStorageValue" /><br />
<button onclick="setSessionStorage()">SetSessionStorage</button><br /><br />
Name：<input type="text" id="getSessionStorageName" /> = <input type="text" id="getSessionStorageValue" /><br />
<button onclick="getSessionStorage()">GetSessionStorage</button><br />
<button onclick="removeSessionStorage()">RemoveSessionStorage</button><br /><br /><br />


<script type="text/javascript">

    function setClientCookie() {
        var name = document.querySelector("#setCookieName").value;
        var value = document.querySelector("#setCookieValue").value;
        var storage = new clientStorage();
        storage.setCookie(name, value, 1);
    }

    function getClientCookie() {
        var name = document.querySelector("#getCookieName").value;
        var display = document.querySelector("#getCookieValue");
        var storage = new clientStorage();
        display.value = storage.getCookie(name);
    }

    function removeClientCookie() {
        var name = document.querySelector("#getCookieName").value;
        var value = document.querySelector("#getCookieValue");
        var storage = new clientStorage();
        storage.removeCookie(name);
    }

    function setLocalStorage() {
        var name = document.querySelector("#setLocalStorageName").value;
        var value = document.querySelector("#setLocalStorageValue").value;
        var storage = new clientStorage();
        storage.setLocalStorage(name, value, 1);
    }

    function getLocalStorage() {
        var name = document.querySelector("#getLocalStorageName").value;
        var display = document.querySelector("#getLocalStorageValue");
        var storage = new clientStorage();
        display.value = storage.getLocalStorage(name);
    }

    function removeLocalStorage() {
        var name = document.querySelector("#getLocalStorageName").value;
        var value = document.querySelector("#getLocalStorageValue");
        var storage = new clientStorage();
        storage.removeLocalStorage(name);
    }

    function setSessionStorage() {
        var name = document.querySelector("#setSessionStorageName").value;
        var value = document.querySelector("#setSessionStorageValue").value;
        var storage = new clientStorage();
        storage.setSessionStorage(name, value, 1);
    }

    function getSessionStorage() {
        var name = document.querySelector("#getSessionStorageName").value;
        var display = document.querySelector("#getSessionStorageValue");
        var storage = new clientStorage();
        display.value = storage.getSessionStorage(name);
    }

    function removeSessionStorage() {
        var name = document.querySelector("#getSessionStorageName").value;
        var value = document.querySelector("#getSessionStorageValue");
        var storage = new clientStorage();
        storage.removeSessionStorage(name);
    }

    function clientStorage() {
        return {
            setCookie: function (cname, cvalue, exdays) {
                var d = new Date();
                d.setTime(d.getTime() + (exdays * 24 * 60 * 60 * 1000));
                var expires = "expires=" + d.toUTCString();
                document.cookie = cname + "=" + cvalue + ";" + expires + ";path=/";
            },
            getCookie: function (cname) {
                var name = cname + "=";
                var decodedCookie = decodeURIComponent(document.cookie);
                var ca = decodedCookie.split(';');
                for (var i = 0; i < ca.length; i++) {
                    var c = ca[i];
                    while (c.charAt(0) == ' ') {
                        c = c.substring(1);
                    }
                    if (c.indexOf(name) == 0) {
                        return c.substring(name.length, c.length);
                    }
                }
                return "";
            },
            removeCookie: function (cname) {
                this.setCookie(cname, "", 0);
            },
            setLocalStorage: function (cname, cvalue) {
                localStorage.setItem(cname, cvalue);
            },
            getLocalStorage: function (cname) {
                return localStorage.getItem(cname);
            },
            removeLocalStorage: function (cname) {
                localStorage.removeItem(cname);
            },
            setSessionStorage: function (cname, cvalue) {
                sessionStorage.setItem(cname, cvalue);
            },
            getSessionStorage: function (cname) {
                return sessionStorage.getItem(cname);
            },
            removeSessionStorage: function (cname) {
                sessionStorage.removeItem(cname);
            },
        };
    }


</script>